// src/sidebar/view/iconMap.ts

/**
 * Mapping Extension -> SVG Filename (tanpa .svg)
 * Berdasarkan daftar aset VS Code Material Icon Theme.
 */
export const FILE_ICON_MAP: Record<string, string> = {
    // --- Generic / Common ---
    'txt': 'default_file',
    'md': 'file_type_markdown',
    'xml': 'file_type_xml',
    'json': 'file_type_json',
    'jsonc': 'file_type_json',
    'yaml': 'file_type_yaml',
    'yml': 'file_type_yaml',
    'csv': 'file_type_text',
    'log': 'file_type_log',
    'zip': 'file_type_zip',
    'tar': 'file_type_zip',
    'gz': 'file_type_zip',
    'pdf': 'file_type_pdf',
    'svg': 'file_type_svg',
    'png': 'file_type_image',
    'jpg': 'file_type_image',
    'jpeg': 'file_type_image',
    'gif': 'file_type_image',
    'ico': 'file_type_image',
    
    // --- Web Development ---
    'html': 'file_type_html',
    'htm': 'file_type_html',
    'css': 'file_type_css',
    'scss': 'file_type_scss',
    'sass': 'file_type_sass',
    'less': 'file_type_less',
    'styl': 'file_type_stylus',
    'js': 'file_type_js',
    'mjs': 'file_type_js',
    'cjs': 'file_type_js',
    'jsx': 'file_type_reactjs',
    'ts': 'file_type_typescript',
    'cts': 'file_type_typescript',
    'mts': 'file_type_typescript',
    'tsx': 'file_type_reactts',
    'vue': 'file_type_vue',
    'svelte': 'file_type_svelte',
    'astro': 'file_type_astro',
    'php': 'file_type_php',
    
    // --- Backend / Systems ---
    'py': 'file_type_python',
    'pyc': 'file_type_python',
    'pyd': 'file_type_python',
    'java': 'file_type_java',
    'class': 'file_type_class',
    'jar': 'file_type_jar',
    'c': 'file_type_c',
    'h': 'file_type_cheader',
    'cpp': 'file_type_cpp',
    'hpp': 'file_type_cppheader',
    'cs': 'file_type_csharp',
    'go': 'file_type_go',
    'rs': 'file_type_rust',
    'rb': 'file_type_ruby',
    'erb': 'file_type_erb',
    'lua': 'file_type_lua',
    'luau': 'file_type_luau',
    'pl': 'file_type_perl',
    'sh': 'file_type_shell',
    'bash': 'file_type_shell',
    'zsh': 'file_type_shell',
    'bat': 'file_type_bat',
    'cmd': 'file_type_bat',
    'ps1': 'file_type_powershell',
    'sql': 'file_type_sql',
    'db': 'file_type_sqlite',
    'sqlite': 'file_type_sqlite',
    'prisma': 'file_type_prisma',
    'graphql': 'file_type_graphql',
    'gql': 'file_type_graphql',
    
    // --- Config / Tools ---
    'env': 'file_type_dotenv',
    'gitignore': 'file_type_git',
    'gitattributes': 'file_type_git',
    'dockerfile': 'file_type_docker',
    'dockerignore': 'file_type_docker',
    'editorconfig': 'file_type_editorconfig',
    'eslintrc': 'file_type_eslint',
    'eslintignore': 'file_type_eslint',
    'prettierrc': 'file_type_prettier',
    'babelrc': 'file_type_babel',
    'toml': 'file_type_toml',
    'ini': 'file_type_ini',
    'conf': 'file_type_config', // Digunakan untuk config umum (nginx dihapus dari sini)
    'config': 'file_type_config',
    'lock': 'file_type_lock',
    
    // --- Specific Technologies ---
    'dart': 'file_type_dartlang',
    'flutter': 'file_type_flutter',
    'swift': 'file_type_swift',
    'kt': 'file_type_kotlin',
    'kts': 'file_type_kotlin',
    'r': 'file_type_r',
    'ex': 'file_type_elixir',
    'exs': 'file_type_elixir',
    'fs': 'file_type_fsharp',
    'vim': 'file_type_vim',
    'tf': 'file_type_terraform',
    'tfvars': 'file_type_terraform',
    'sol': 'file_type_solidity',
    'gradle': 'file_type_gradle',
    'properties': 'file_type_light_config',
    'csproj': 'file_type_csproj',
    'sln': 'file_type_sln',
    'vb': 'file_type_vb',
    'coffee': 'file_type_coffeescript',
    'blade.php': 'file_type_blade',
    'twig': 'file_type_twig',
    'liquid': 'file_type_liquid',
    'pug': 'file_type_pug',
    'jade': 'file_type_pug',
    'haml': 'file_type_haml',
    'tex': 'file_type_tex',
    'sty': 'file_type_tex',
    'pp': 'file_type_puppet',
    'fish': 'file_type_shell',
    'groovy': 'file_type_groovy',
    'nginx': 'file_type_nginx',
    'makefile': 'file_type_source',
    'jenkinsfile': 'file_type_jenkins',
    'vagrantfile': 'file_type_vagrant',
};

/**
 * Mapping Nama File Spesifik (Exact Match)
 * Prioritas lebih tinggi daripada ekstensi.
 */
export const EXACT_FILE_MAP: Record<string, string> = {
    'package.json': 'file_type_npm',
    'package-lock.json': 'file_type_npm',
    'yarn.lock': 'file_type_yarn',
    'pnpm-lock.yaml': 'file_type_pnpm',
    'bun.lockb': 'file_type_bun',
    'composer.json': 'file_type_composer',
    'composer.lock': 'file_type_composer',
    'cargo.toml': 'file_type_cargo',
    'cargo.lock': 'file_type_cargo',
    'go.mod': 'file_type_go_package',
    'go.sum': 'file_type_go_package',
    'requirements.txt': 'file_type_python',
    'pipfile': 'file_type_python',
    'dockerfile': 'file_type_docker',
    'docker-compose.yml': 'file_type_docker',
    'docker-compose.yaml': 'file_type_docker',
    'makefile': 'file_type_source',
    'gulpfile.js': 'file_type_gulp',
    'gruntfile.js': 'file_type_grunt',
    'jest.config.js': 'file_type_jest',
    'jest.config.ts': 'file_type_jest',
    'tailwind.config.js': 'file_type_tailwind',
    'tailwind.config.ts': 'file_type_tailwind',
    'postcss.config.js': 'file_type_postcss',
    'vite.config.js': 'file_type_vite',
    'vite.config.ts': 'file_type_vite',
    'webpack.config.js': 'file_type_webpack',
    'next.config.js': 'file_type_next',
    'nuxt.config.js': 'file_type_nuxt',
    'tsconfig.json': 'file_type_tsconfig',
    'jsconfig.json': 'file_type_jsconfig',
    'readme.md': 'file_type_info',
    'license': 'file_type_license',
    'license.txt': 'file_type_license',
    'changelog.md': 'file_type_info',
    '.gitignore': 'file_type_git',
    '.gitattributes': 'file_type_git',
    '.env': 'file_type_dotenv',
    '.env.local': 'file_type_dotenv',
    '.env.example': 'file_type_dotenv',
    '.editorconfig': 'file_type_editorconfig',
    'procfile': 'file_type_procfile',
};

/**
 * Mapping Folder Khusus (jika di masa depan ingin dipakai untuk logika lain)
 */
export const FOLDER_ICON_MAP: Record<string, string> = {
    'src': 'folder_type_src',
    'dist': 'folder_type_dist',
    'build': 'folder_type_dist',
    'out': 'folder_type_dist',
    'node_modules': 'folder_type_node',
    'assets': 'folder_type_asset',
    'images': 'folder_type_images',
    'img': 'folder_type_images',
    'components': 'folder_type_component',
    'services': 'folder_type_services',
    'utils': 'folder_type_tools',
    'helpers': 'folder_type_helper',
    'tests': 'folder_type_test',
    '__tests__': 'folder_type_test',
    'docs': 'folder_type_docs',
    'api': 'folder_type_api',
    'lib': 'folder_type_library',
    'include': 'folder_type_include',
    'styles': 'folder_type_style',
    'css': 'folder_type_css',
    'view': 'folder_type_view',
    'views': 'folder_type_view',
    'controllers': 'folder_type_controller',
    'routes': 'folder_type_route',
    'public': 'folder_type_public',
    '.git': 'folder_type_git',
    '.github': 'folder_type_github',
    '.vscode': 'folder_type_vscode',
};